### ISSUE TITLE
Solid region shapes aren't rendered at all

### ISSUE THREAD

**Issue by turbobabr** [turbobabr/easyeda-ibom-extension#14]
![image](https://user-images.githubusercontent.com/6356526/121184153-61b80980-c897-11eb-92da-545368bb2aef.png)

[iBom_solid_regions_rendering_issues_2021-06-08.json.zip](https://github.com/turbobabr/easyeda-ibom-extension/files/6616357/iBom_solid_regions_rendering_issues_2021-06-08.json.zip)

**Comment by xsrf** [comment]
You were faster than me opening the issue ;) However, I think you missed filtering the `SOLIDREGION` for `type: "solid"`. There is also `type: "cutout"` which shouldn't be rendered as copper area.

**Comment by turbobabr** [comment]
Ugh... completely forgot about additional modes - thank you for pointing out. Added a filter in this release:
- https://github.com/turbobabr/easyeda-ibom-extension/releases/download/v0.1.2/easyeda-ibom-v0.1.2.zip
