### ISSUE TITLE
Copper features inside footprints not rendered

### ISSUE THREAD

**Issue by xsrf** [turbobabr/easyeda-ibom-extension#15]
Footprints can have their own Tracks, solid regions or Images (SVGNodes) potentially containing copper or silkscreen. At the moment these are not rendered at all which makes some footprints hard to identify on the pcb preview.
I think these features should just be rendered as if they were part of the PCB itself.

Since the datamodel of these features is the same as for the features on the PCB itself, they could just be copied from the footprint to the PCB data before rendering.

![2021-06-06 21_50_45-EasyEDA(Standard) - A Simple and Powerful Electronic Circuit Design Tool](https://user-images.githubusercontent.com/8081353/121194648-39b4b000-c86f-11eb-9ed6-c25009bb64f9.png)

**Comment by turbobabr** [comment]
Managed to do some work with additional shape types, guessing there will be bugs... :)

Available here:
- https://github.com/turbobabr/easyeda-ibom-extension/releases/download/v0.1.2/easyeda-ibom-v0.1.2.zip

**Comment by xsrf** [comment]
That actually works pretty good already 👍

I've noticed `CIRCLE` support is also missing completely 🙈

**Comment by turbobabr** [comment]
> That actually works pretty good already 👍
Awesome! 🚀 

> I've noticed CIRCLE support is also missing completely 🙈
Yeah.. `CIRCLE`s and `ARC`'s are missing atm -will add them a bit later.

**Comment by xsrf** [comment]
Made a horrible example 😄

![2021-06-08 17_40_13-EasyEDA(Standard) - A Simple and Powerful Electronic Circuit Design Tool](https://user-images.githubusercontent.com/8081353/121215833-a2f0ef00-c880-11eb-8e53-25067848859c.png)
![2021-06-08 17_38_28-EasyEDA(Standard) - A Simple and Powerful Electronic Circuit Design Tool](https://user-images.githubusercontent.com/8081353/121215656-7dfc7c00-c880-11eb-9084-62d172654a80.png)

**Comment by turbobabr** [comment]
Could you share the JSON source for this one? Will add it to my "canonical" tests.

**Comment by xsrf** [comment]
Sure... the tilted part is actually the footprint `__TEST_IBOM_ISSUE`


[PCB_ibom_2021-06-08.json.txt](https://github.com/turbobabr/easyeda-ibom-extension/files/6617971/PCB_ibom_2021-06-08.json.txt)

**Comment by turbobabr** [comment]
Cool! Thanks!
