### ISSUE TITLE
Wrong position on some highlighted parts

### ISSUE THREAD

**Issue by vlrmprjct** [turbobabr/easyeda-ibom-extension#2]
Looks like some parts have a mirrored position.
I dont know is it an EasyEDA Issue or a extension issue.

See Screens:
![image](https://user-images.githubusercontent.com/1859497/111214073-c6820180-85d1-11eb-8799-37c9027a62a7.png)
![image](https://user-images.githubusercontent.com/1859497/111214113-d4d01d80-85d1-11eb-8f84-3d7b27ac2955.png)

**Comment by xsrf** [comment]
I noticed the same, usually on connectors. Looks like the highlight frame is always centered around the component origin, so it is offset for components which don't have their origin in their center.

![2021-03-15 21_34_51-EasyEDA(Standard) - A Simple and Powerful Electronic Circuit Design Tool](https://user-images.githubusercontent.com/8081353/111217973-7194ba00-85d6-11eb-8018-722925435a8c.png)
![2021-03-15 21_35_18-EasyEDA(Standard) - A Simple and Powerful Electronic Circuit Design Tool](https://user-images.githubusercontent.com/8081353/111217990-76596e00-85d6-11eb-9876-121a8feafbd4.png)

**Comment by turbobabr** [comment]
Wow! "Dark" guys are here! :) Thank you for reporting the bug!

@xsrf Yup.. that's the line, just fixed it. The updated version is here:
- https://github.com/turbobabr/easyeda-ibom-extension/releases/download/v0.0.7/easyeda-ibom-v0.0.7.zip
